routes/web.php
<?php

use App\Http\Controllers\{
    DashboardController,
    KategoriController,
    LaporanController,
    ProdukController,
    MemberController,
    PemasukanController,
    PengeluaranController,
    PembelianController,
    PembelianDetailController,
    PenjualanController,
    PenjualanDetailController,
    SettingController,
    SupplierController,
    UserController,
    PayController,
};
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});
Route::get('/pay/{id}', [PayController::class, 'index']);
Route::get('pay/redirect_midtrans/{id}', 'PayController@redirect_midtrans')->name('pay.redirect_midtrans');
Route::get('notification', [PayController::class, 'notification_payment']);
Route::post('notification', [PayController::class, 'notification_payment']);
// Route::post('notification', 'PayController@notification_payment');
// Route::get('notification', 'PayController@notification_payment');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::group(['middleware' => 'level:admin'], function () {
        Route::get('/kategori/data', [KategoriController::class, 'data'])->name('kategori.data');
        Route::resource('/kategori', KategoriController::class);

        Route::get('/produk/data', [ProdukController::class, 'data'])->name('produk.data');
        Route::post('/produk/delete-selected', [ProdukController::class, 'deleteSelected'])->name('produk.delete_selected');
        Route::post('/produk/cetak-barcode', [ProdukController::class, 'cetakBarcode'])->name('produk.cetak_barcode');
        Route::resource('/produk', ProdukController::class);
        Route::get('/stok', [ProdukController::class, 'stok'])->name('produk.stok');

        Route::get('/member/data', [MemberController::class, 'data'])->name('member.data');
        Route::post('/member/cetak-member', [MemberController::class, 'cetakMember'])->name('member.cetak_kartu');
        Route::resource('/member', MemberController::class);

        Route::get('/supplier/data', [SupplierController::class, 'data'])->name('supplier.data');
        Route::resource('/supplier', SupplierController::class);

        Route::get('/pengeluaran/data', [PengeluaranController::class, 'data'])->name('pengeluaran.data');
        Route::resource('/pengeluaran', PengeluaranController::class);

        Route::get('/pemasukan/data', [PemasukanController::class, 'data'])->name('pemasukan.data');
        Route::resource('/pemasukan', PemasukanController::class);



        Route::get('/pembelian/data', [PembelianController::class, 'data'])->name('pembelian.data');
        Route::get('/pembelian/{id}/create', [PembelianController::class, 'create'])->name('pembelian.create');
        Route::resource('/pembelian', PembelianController::class)
            ->except('create');

        Route::get('/pembelian_detail/{id}/data', [PembelianDetailController::class, 'data'])->name('pembelian_detail.data');
        Route::get('/pembelian_detail/loadform/{diskon}/{total}', [PembelianDetailController::class, 'loadForm'])->name('pembelian_detail.load_form');
        Route::resource('/pembelian_detail', PembelianDetailController::class)
        ->except('create', 'show', 'edit');
    });
    Route::group(['middleware' => 'level:admin,kasir'], function () {
        Route::get('/penjualan/data', [PenjualanController::class, 'data'])->name('penjualan.data');
        Route::get('/penjualan', [PenjualanController::class, 'index'])->name('penjualan.index');
        Route::get('/penjualan/{id}', [PenjualanController::class, 'show'])->name('penjualan.show');
        Route::delete('/penjualan/{id}', [PenjualanController::class, 'destroy'])->name('penjualan.destroy');
        Route::resource('midtrans', PenjualanController::class)->only(['index', 'show']);
         Route::post('/penjualan/delete-selected', [PenjualanController::class, 'deleteSelected'])->name('penjualan.delete_selected');
    });

    Route::group(['middleware' => 'level:admin,kasir'], function () {
        Route::get('/transaksi/baru', [PenjualanController::class, 'create'])->name('transaksi.baru');
        Route::post('/transaksi/simpan', [PenjualanController::class, 'store'])->name('transaksi.simpan');
        Route::get('/transaksi/selesai', [PenjualanController::class, 'selesai'])->name('transaksi.selesai');
        Route::get('/transaksi/nota-kecil', [PenjualanController::class, 'notaKecil'])->name('transaksi.nota_kecil');
        Route::get('/transaksi/nota-besar', [PenjualanController::class, 'notaBesar'])->name('transaksi.nota_besar');

        Route::get('/transaksi/{id}/data', [PenjualanDetailController::class, 'data'])->name('transaksi.data');
        Route::get('/transaksi/loadform/{diskon}/{total}/{diterima}', [PenjualanDetailController::class, 'loadForm'])->name('transaksi.load_form');
        Route::resource('/transaksi', PenjualanDetailController::class)
            ->except('create', 'show', 'edit');
    });

    Route::group(['middleware' => 'level:admin'], function () {
        Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan.index');
        Route::get('/laporan/data/{awal}/{akhir}', [LaporanController::class, 'data'])->name('laporan.data');
        Route::get('/laporan/pdf/{awal}/{akhir}', [LaporanController::class, 'exportPDF'])->name('laporan.export_pdf');

        Route::get('/user/data', [UserController::class, 'data'])->name('user.data');
        Route::resource('/user', UserController::class);

        Route::get('/setting', [SettingController::class, 'index'])->name('setting.index');
        Route::get('/setting/first', [SettingController::class, 'show'])->name('setting.show');
        Route::post('/setting', [SettingController::class, 'update'])->name('setting.update');
    });

    Route::group(['middleware' => 'level:admin,kasir'], function () {
        Route::get('/profil', [UserController::class, 'profil'])->name('user.profil');
        Route::post('/profil', [UserController::class, 'updateProfil'])->name('user.updateProfil');
    });

});

app/Models/PenjualanDetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PenjualanDetail extends Model
{
    use HasFactory;
    protected $table = 'penjualan_detail';
    protected $primaryKey = 'id_penjualan_detail';
    protected $guarded = [];

    public function produk()
    {
        return $this->hasOne(Produk::class, 'id_produk', 'id_produk');
    }
    public function pembelian_detail()
    {
        return $this->hasOne(PembelianDetail::class, 'id_produk', 'id_produk');
    }
}

app/Http/Controllers/PenjualanDetailController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Produk;
use App\Models\Member;
use App\Models\Setting;
use App\Models\PenjualanDetail;
use App\Models\Penjualan;

class PenjualanDetailController extends Controller
{
    public function index()
    {
        $produk = Produk::orderBy('nama_produk')->get();
        $member = Member::orderBy('nama')->get();
        $diskon = Setting::first()->diskon ?? 0;

        if($id_penjualan = session('id_penjualan')){
            $penjualan = Penjualan::find($id_penjualan);
            $memberSelected = $penjualan->member ?? new Member();
            return view('penjualan_detail.index', compact('produk', 'member', 'diskon', 'id_penjualan', 'penjualan', 'memberSelected'));
        }

        if (auth()->user()->level == 1) {
            return redirect()->route('transaksi.baru');
        }else{
            return redirect()->route('home');
        }
    }

    public function data($id)
    {
        $detail = PenjualanDetail::with('produk')
        ->where('id_penjualan', $id)
        ->get();
    
        $data = array();
        $total = 0;
        $total_item = 0;

        foreach ($detail as $item) {
            $row = array();
            $row ['kode_produk'] = '<span class="label label-primary">'. $item->produk['kode_produk'] .'</span>';
            $row ['nama_produk'] = $item->produk['nama_produk'];
            $row ['harga_jual']  = 'Rp '. format_uang($item->harga_jual);
            $row ['jumlah']      = '<input type="number" class="form-control input-sm quantity" data-id="'. $item->id_penjualan_detail .'" data-stok="'. $item->produk->stok .'" value="'. $item->jumlah .'" >';
            $row ['diskon']      =  $item->diskon . '%';
            $row ['subtotal']    = 'Rp '. format_uang($item->subtotal);
            $row ['action']      = '<div class="btn-group">
                                    <button onclick="deleteData(`'. route('transaksi.destroy', $item->id_penjualan_detail) .'`)" class= "btn btn-xs btn-danger"><i class= "fa fa-trash"></i></button>
                                    </div>';
            $data[] = $row;

            $total += $item->harga_jual * $item->jumlah;
            $total_item += $item->jumlah;

        }

        $data[] = [
            'kode_produk' => '<div class="total hide">'. $total .'</div>
                            <div class="total_item hide">'. $total_item .'</div>',
            'nama_produk' => '',
            'harga_jual' => '',
            'jumlah' => '',
            'diskon' => '',
            'subtotal' => '',
            'action' => '',

        ];

        
        return datatables()
        ->of($data)
        ->addIndexColumn()
        ->rawColumns(['action', 'kode_produk', 'harga_jual', 'subtotal', 'jumlah'])
        ->make(true);
    }

    public function loadForm($diskon, $total, $diterima)
    {
        $bayar = $total - ($diskon / 100 * $total);
        $kembali = ($diterima != 0) ? $diterima - $bayar : 0;
        $data = [
            'totalrp' => format_uang($total),
            'bayar' => $bayar,
            'bayarrp' => format_uang($bayar),
            'terbilang' => ucwords(terbilang($bayar).' Rupiah'),
            'kembalirp' => format_uang($kembali),
            'kembali_terbilang' => ucwords(terbilang($kembali).' Rupiah'),
        ];
        return response()->json($data);
    
    }

    public function create()
    {

    }

    public function store(Request $request)
    {
        $produk = Produk::where('id_produk', $request->id_produk)->first();
        if (! $produk) {
            return response()->json('Data gagal Disimpan', 400);
        }
        $detail = new PenjualanDetail();
        $detail->id_penjualan = $request->id_penjualan;
        $detail->id_produk = $produk->id_produk;
        $detail->harga_jual = $produk->harga_jual;
        $detail->jumlah = 1;
        $detail->diskon = 0;
        $detail->subtotal = $produk->harga_jual;
        $detail->save();

        return response()->json('Data berhasil Disimpan', 200);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        $detail = PenjualanDetail::find($id);
        $detail->jumlah = $request->jumlah;
        $detail->subtotal = $detail->harga_jual * $request->jumlah;
        $detail->update();
    }

    public function destroy($id)
    {
        $detail = PenjualanDetail::find($id);
        $detail->delete();
        return response()->json(null, 204);
    }
}

resources/views/penjualan_detail/index.blade.php
@extends('layouts.master')
@section('title')
Transaksi Penjualan
@endsection
@push('css')
<style>
    .tampil-terbilang {
        padding: 10px;
        background: #f0f0f0;
        font-style: italic;
    }

    .table-penjualan tbody tr:last-child {
        display: none;
    }

    @media(max-width: 768px) {
        .tampil-bayar {
            font-size: 3em;
            height: 70px;
            padding-top: 5px;
        }
    }
</style>

@endpush

@section('content')
<div class="col-lg-4">
    <div class="ibox">
        <div class="ibox-content">
            <h2 class="m-b-md">{{ tanggal_indonesia($penjualan->created_at, false) }}</h2>
            <h5 class="text-navy">Nama Kasir :
                {{ strtoupper(auth()->user()->name) }}
            </h5>
            <div class="form-group row">
                <div class="col-lg-8">
                    <div class="input-group" onclick="tampilMember()">
                        <input type="text" class="form-control" id="nama" value="{{ $memberSelected->nama }}"
                            placeholder="Masukkan Member">
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-primary"><i class="fa fa-chevron-right"></i></button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-4">
    <div class="ibox">
        <div class="ibox-content">
            <form class="form-produk">
                @csrf
                <div class="form-group">
                    <div class="input-group col-md-12" onclick=" tampilProduk()">
                        <input type="hidden" name="id_produk" id="id_produk">
                        <input type="hidden" name="id_penjualan" id="id_penjualan" value="{{ $id_penjualan }}">
                        <input type="text" class="form-control" name="kode_produk" id="kode_produk"
                            placeholder="Pilih Produk...">
                        <div class="input-group-addon"><i class="fa fa-search"></i></div>
                    </div>
                </div>
                <hr>
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" oninput="inputProduk()" class="form-control" id="inputBarcode"
                            placeholder="Scan Produk">
                        <div class="input-group-addon"><i class="fa fa-barcode"></i></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="col-lg-4">
    <div class="ibox">
        <div class="ibox-content">
            <strong class="pull-right text-navy">No Transaksi :
                INV-{{ tambah_nol_didepan($penjualan->id_penjualan, 8) }}</strong>
            <br>
            <h4 class="bayar-kembali"></h4>
            <h2 class="text-navy tampil-bayar"></h2>
            <h6 class="tampil-terbilang"></h6>
        </div>
    </div>
</div>
<div class="col-lg-8">
    <div class="ibox float-e-margins">
        <div class="ibox-content">
            <div class="table-responsive m-t">
                <table class="table table-striped table-bordered table-hover table-penjualan">
                    <thead>
                        <th width="2%">No</th>
                        <th>Kode</th>
                        <th>Nama</th>
                        <th>Harga</th>
                        <th width="5%">Jumlah</th>
                        <th width="5%">diskon</th>
                        <th>Subtotal</th>
                        <th width="15%"><i class="fa fa-cog"></i></th>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="col-lg-4 pull-right">
    <div class="ibox">
        <div class="ibox-content">
            <div class="row">
                <form action="{{ route('transaksi.simpan') }}" class="form-penjualan" method="post">
                    @csrf
                    <input type="hidden" name="id_penjualan" value="{{ $id_penjualan }}">
                    <input type="hidden" name="total" id="total">
                    <input type="hidden" name="total_item" id="total_item">
                    <input type="hidden" name="bayar" id="bayar">
                    <input type="hidden" name="id_member" id="id_member" value="{{ $memberSelected->nama }}">

                    <div class="form-group row">
                        <label for="totalrp" class="col-lg-3 control-label">Total</label>
                        <div class="col-lg-8">
                            <input type="text" id="totalrp" class="form-control" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="diskon" class="col-lg-3 control-label">Diskon</label>
                        <div class="col-lg-8">
                            <input type="number" name="diskon" id="diskon" class="form-control"
                                value="{{ ! empty($memberSelected->nama) ? $diskon : 0 }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="bayar" class="col-lg-3 control-label">Bayar</label>
                        <div class="col-lg-8">
                            <input type="text" id="bayarrp" class="form-control" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="diterima" class="col-lg-3 control-label">Diterima</label>
                        <div class="col-lg-8">
                            <input type="number" id="diterima" name="diterima" class="form-control"
                                value="{{ $penjualan->diterima ?? 0 }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="metode_pembayaran" class="col-lg-3 control-label">Metode Pembayaran</label>
                        <div class="col-lg-8">
                            <select name="metode_pembayaran" id="metode_pembayaran" class="form-control">
                                <option>Tunai</option>
                                <option>Transfer</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="kembali" class="col-lg-3 control-label">Kembali</label>
                        <div class="col-lg-8">
                            <input type="text" id="kembali" class="form-control" value="0" readonly>
                        </div>
                    </div>
                </form>
            </div>
            <div class="ibox-footer m-sm">
                <button type="submit" class="btn btn-success btn-outline btn-xs dim pull-right btn-simpan"><i
                        class="fa fa-floppy-o"></i> Simpan Transaksi</button>
            </div>
        </div>
    </div>
</div>

@includeIf('penjualan_detail.produk')
@includeIf('penjualan_detail.member')
@endsection

@push('scripts')
<script>
    let table, table2;

    $(function () {
        $('body').addClass('sidebar-collapse mini-navbar');
        table = $('.table-penjualan').DataTable({
            processing: true,
            autoWidth: false,
            ajax: {
                url: '{{ route('transaksi.data', $id_penjualan) }}',
            },
            columns: [
                {data: 'DT_RowIndex', searchable: false, sortable: false},
                {data: 'kode_produk'},
                {data: 'nama_produk'},
                {data: 'harga_jual'},
                {data: 'jumlah'},
                {data: 'diskon'},
                {data: 'subtotal'},
                {data: 'action', searchable: false, sortable: false},
            ],
            dom: 'brt',
            bSort: false,
            paginate: false
        })
        .on('draw.dt', function (){
            loadForm($('#diskon').val());
            setTimeout(() => {
                $('#diterima').trigger('input');
            }, 300);
        });
    table2 = $('.table-produk').DataTable();

    $(document).on('input', '.quantity', function(){
        let id = $(this).data('id');
        let jumlah= parseInt($(this).val());
        let stok = $(this).attr("data-stok");

        if (jumlah > stok) {
            $(this).val(0);
            swal("Peringatan!", "Jumlah tidak boleh lebih dari stok", "error");
            return;
        }
        if (jumlah < 1) {
            $(this).val(1);
            swal("Peringatan!", "Jumlah tidak boleh kurang dari 1", "error");
            return;
        }
        if (jumlah > 100000) {
            $(this).val(99999);
            swal("Peringatan!", "Jumlah tidak boleh lebih dari 100000", "error");
            return;
        }

        $.post(`{{ url('/transaksi') }}/${id}`, {
            '_token': $('[name=csrf-token]').attr('content'),
            '_method': 'put',
            'jumlah': jumlah
        })
            .done(response => {
                $(this).on('mouseout', function () {
                table.ajax.reload();
                })
            })
            .fail(errors => {
                
            })
        });

        $(document).on('input', '#diskon', function() {
            if ($(this).val()=="") {
                $(this).val(0).select();
            }
            loadForm($(this).val());
        });

        $('#diterima').on('input', function() {
           if ($(this).val() == "") {
               $(this).val(0).select();
           } 
           loadForm($('#diskon').val(), $(this).val());
        }).focus(function () {
            $(this).select();
        });

        $('.btn-simpan').on('click', function() {
            let diterima= parseInt($('#diterima').val());
            let bayar= parseInt($('#bayar').val());
            let metode_pembayaran= ($('#metode_pembayaran').val());
            if(metode_pembayaran == 'Tunai'){
                if (diterima < bayar) {
                swal("Peringatan!", "Uang yang diterima kurang untuk pembayaran tunai", "error");
                return;
                }
            }
            if (bayar == 0) {
            swal("Peringatan!", "Masukkan Transaksi", "error");
            return;
            }
            $('.form-penjualan').submit();

        });
    });
    function tampilProduk(){
        $('#modal-produk').modal('show');
    }
    function hideProduk(){
        $('#modal-produk').modal('hide');
    }
    function tampilMember(){
        $('#modal-member').modal('show');
    }

    function pilihMember(id, nama){
        $('#id_member').val(id);
        $('#nama').val(nama);
        $('#diskon').val('{{ $diskon }}');
        loadForm($('#diskon').val());
        $('#diterima').val(0).focus().select();
        hideMember();
    }

    function hideMember(){
        $('#modal-member').modal('hide');
    }

    function tambahProduk(){
        $.post('{{ route('transaksi.store') }}', $('.form-produk').serialize())
        .done(response => {
            $('#kode_produk').focus();
            table.ajax.reload();
        })
        .fail(errors => {
            alert('error');
            return;
        })
    }
    function tambahProdukdariBarcode(){
        $.post('{{ route('transaksi.store') }}', $('.form-produk').serialize())
        .done(response => {
            table.ajax.reload();
            $('#inputBarcode').focus().val('');
        })
        .fail(errors => {
            alert('Barcode tidak valid');
            return;
        })
    }

    function pilihProduk(id, kode){
        $('#id_produk').val(id);
        $('#kode_produk').val(kode);
        hideProduk();
        tambahProduk();
    }
    function inputProduk(){
        var input = document.getElementById("inputBarcode").value;
        document.getElementById("id_produk").value = input;
        tambahProdukdariBarcode();
    }


    function deleteData(url){
        swal({
            title: "Peringatan!",
            text: "Apakah anda yakin?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Ya, Hapus",
            closeOnConfirm: false
        },
        function () {
        $.post(url, {
        '_token': $('[name=csrf-token]').attr('content'),
        '_method': 'delete'
        })
        .done((response) => {
        swal("Deleted!", "Data berhasil terhapus", "success");
        table.ajax.reload();
        });
        });
    }

    function loadForm(diskon = 0, diterima = 0){
        $('#total').val($('.total').text());
        $('#total_item').val($('.total_item').text());

        $.get(`{{ url('/transaksi/loadform') }}/${diskon}/${$('.total').text()}/${diterima}`)
            .done(response => {
                $('#totalrp').val('Rp '+response.totalrp);
                $('#bayarrp').val('Rp '+response.bayarrp);
                $('#bayar').val(response.bayar);
                $('.bayar-kembali').text('Total Bayar');
                $('.tampil-bayar').text('Rp '+ response.bayarrp);
                $('.tampil-terbilang').text(response.terbilang);

                $('#kembali').val('Rp '+ response.kembalirp);
                if ($('#diterima').val() != 0) {
                    $('.bayar-kembali').text('Uang Kembali');
                    $('.tampil-bayar').text('Rp '+ response.kembalirp);
                    $('.tampil-terbilang').text(response.kembali_terbilang);
                }
            })
            .fail(errors => {
                alert('error');
                return;
            })
    }


    
</script>
@endpush

resources/views/penjualan_detail/member.blade.php
<div class="modal inmodal" id="modal-member" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content animated fadeIn">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <i class="fa fa-vcard modal-icon"></i>
                <h4 class="modal-title">Pilih Member</h4>
            </div>
            <div class="modal-body">
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover table-member">
                            <thead>
                                <th width="2%">No</th>
                                <th>Nama</th>
                                <th>Telepon</th>
                                <th>Alamat</th>
                                <th width="5%"><i class="fa fa-cog"></i></th>
                            </thead>
                            <tbody>
                                @foreach ($member as $key => $item)
                                <tr>
                                    <td width="2%">{{ $key+1 }}</td>
                                    <td>{{ $item->nama }}</td>
                                    <td>{{ $item->telepon }}</td>
                                    <td>{{ $item->alamat }}</td>
                                    <td>
                                        <a href="#" onclick="pilihMember('{{ $item->id_member }}', '{{ $item->nama }}')"
                                            class="btn btn-xs btn-primary"><i class="fa fa-plus-circle">
                                                Pilih</i></a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/penjualan_detail/produk.blade.php
<div class="modal inmodal" id="modal-produk" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content animated fadeIn">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <i class="fa fa-cubes modal-icon"></i>
                <h4 class="modal-title">Pilih Produk</h4>
            </div>
            <div class="modal-body">
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover table-produk">
                            <thead>
                                <th width="2%">No</th>
                                <th>Kode Produk</th>
                                <th>Nama Produk</th>
                                <th>Stok</th>
                                <th>Harga Jual</th>
                                <th width="5%"><i class="fa fa-cog"></i></th>
                            </thead>
                            <tbody>
                                @foreach ($produk as $key => $item)
                                <tr>
                                    <td width="2%">{{ $key+1 }}</td>
                                    <td><span class="label label-primary">{{ $item->kode_produk }}</span></td>
                                    <td>{{ $item->nama_produk }}</td>
                                    <td>
                                        @if ($item->stok >= 1)
                                        {{ $item->stok }}
                                        @else
                                        <p class="text-danger">Stok Habis</p>
                                        @endif
                                    </td>
                                    <td>Rp. {{ format_uang($item->harga_jual) }}</td>
                                    <td>
                                        @if ($item->stok >= 1)
                                        <a onclick="pilihProduk('{{ $item->id_produk }}', '{{ $item->kode_produk }}')"
                                            class="btn btn-xs btn-success">Pilih <i class="fa fa-long-arrow-right">
                                            </i></a>
                                        @else
                                        <a href="#" class="btn btn-xs btn-danger">X</a>
                                        @endif
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>