routes/web.php
<?php

use App\Http\Controllers\{
    DashboardController,
    KategoriController,
    LaporanController,
    ProdukController,
    MemberController,
    PemasukanController,
    PengeluaranController,
    PembelianController,
    PembelianDetailController,
    PenjualanController,
    PenjualanDetailController,
    SettingController,
    SupplierController,
    UserController,
    PayController,
};
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});
Route::get('/pay/{id}', [PayController::class, 'index']);
Route::get('pay/redirect_midtrans/{id}', 'PayController@redirect_midtrans')->name('pay.redirect_midtrans');
Route::get('notification', [PayController::class, 'notification_payment']);
Route::post('notification', [PayController::class, 'notification_payment']);
// Route::post('notification', 'PayController@notification_payment');
// Route::get('notification', 'PayController@notification_payment');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::group(['middleware' => 'level:admin'], function () {
        Route::get('/kategori/data', [KategoriController::class, 'data'])->name('kategori.data');
        Route::resource('/kategori', KategoriController::class);

        Route::get('/produk/data', [ProdukController::class, 'data'])->name('produk.data');
        Route::post('/produk/delete-selected', [ProdukController::class, 'deleteSelected'])->name('produk.delete_selected');
        Route::post('/produk/cetak-barcode', [ProdukController::class, 'cetakBarcode'])->name('produk.cetak_barcode');
        Route::resource('/produk', ProdukController::class);
        Route::get('/stok', [ProdukController::class, 'stok'])->name('produk.stok');

        Route::get('/member/data', [MemberController::class, 'data'])->name('member.data');
        Route::post('/member/cetak-member', [MemberController::class, 'cetakMember'])->name('member.cetak_kartu');
        Route::resource('/member', MemberController::class);

        Route::get('/supplier/data', [SupplierController::class, 'data'])->name('supplier.data');
        Route::resource('/supplier', SupplierController::class);

        Route::get('/pengeluaran/data', [PengeluaranController::class, 'data'])->name('pengeluaran.data');
        Route::resource('/pengeluaran', PengeluaranController::class);

        Route::get('/pemasukan/data', [PemasukanController::class, 'data'])->name('pemasukan.data');
        Route::resource('/pemasukan', PemasukanController::class);



        Route::get('/pembelian/data', [PembelianController::class, 'data'])->name('pembelian.data');
        Route::get('/pembelian/{id}/create', [PembelianController::class, 'create'])->name('pembelian.create');
        Route::resource('/pembelian', PembelianController::class)
            ->except('create');

        Route::get('/pembelian_detail/{id}/data', [PembelianDetailController::class, 'data'])->name('pembelian_detail.data');
        Route::get('/pembelian_detail/loadform/{diskon}/{total}', [PembelianDetailController::class, 'loadForm'])->name('pembelian_detail.load_form');
        Route::resource('/pembelian_detail', PembelianDetailController::class)
        ->except('create', 'show', 'edit');
    });
    Route::group(['middleware' => 'level:admin,kasir'], function () {
        Route::get('/penjualan/data', [PenjualanController::class, 'data'])->name('penjualan.data');
        Route::get('/penjualan', [PenjualanController::class, 'index'])->name('penjualan.index');
        Route::get('/penjualan/{id}', [PenjualanController::class, 'show'])->name('penjualan.show');
        Route::delete('/penjualan/{id}', [PenjualanController::class, 'destroy'])->name('penjualan.destroy');
        Route::resource('midtrans', PenjualanController::class)->only(['index', 'show']);
         Route::post('/penjualan/delete-selected', [PenjualanController::class, 'deleteSelected'])->name('penjualan.delete_selected');
    });

    Route::group(['middleware' => 'level:admin,kasir'], function () {
        Route::get('/transaksi/baru', [PenjualanController::class, 'create'])->name('transaksi.baru');
        Route::post('/transaksi/simpan', [PenjualanController::class, 'store'])->name('transaksi.simpan');
        Route::get('/transaksi/selesai', [PenjualanController::class, 'selesai'])->name('transaksi.selesai');
        Route::get('/transaksi/nota-kecil', [PenjualanController::class, 'notaKecil'])->name('transaksi.nota_kecil');
        Route::get('/transaksi/nota-besar', [PenjualanController::class, 'notaBesar'])->name('transaksi.nota_besar');

        Route::get('/transaksi/{id}/data', [PenjualanDetailController::class, 'data'])->name('transaksi.data');
        Route::get('/transaksi/loadform/{diskon}/{total}/{diterima}', [PenjualanDetailController::class, 'loadForm'])->name('transaksi.load_form');
        Route::resource('/transaksi', PenjualanDetailController::class)
            ->except('create', 'show', 'edit');
    });

    Route::group(['middleware' => 'level:admin'], function () {
        Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan.index');
        Route::get('/laporan/data/{awal}/{akhir}', [LaporanController::class, 'data'])->name('laporan.data');
        Route::get('/laporan/pdf/{awal}/{akhir}', [LaporanController::class, 'exportPDF'])->name('laporan.export_pdf');

        Route::get('/user/data', [UserController::class, 'data'])->name('user.data');
        Route::resource('/user', UserController::class);

        Route::get('/setting', [SettingController::class, 'index'])->name('setting.index');
        Route::get('/setting/first', [SettingController::class, 'show'])->name('setting.show');
        Route::post('/setting', [SettingController::class, 'update'])->name('setting.update');
    });

    Route::group(['middleware' => 'level:admin,kasir'], function () {
        Route::get('/profil', [UserController::class, 'profil'])->name('user.profil');
        Route::post('/profil', [UserController::class, 'updateProfil'])->name('user.updateProfil');
    });

});

resources/views/admin/dashboard.blade.php
@extends('layouts.master')
@section('title')
Dashboard
@endsection

@section('content')
<div class="row">
    <div class="col-lg-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Total Kategori</h5>
            </div>
            <div class="ibox-content">
                <span class="pull-right"><i class="fa fa-cube fa-5x"></i></span>
                <h1 class="no-margins font-bold">{{ $kategori }}</h1>
                <br>
                <a href="{{ route('kategori.index') }}">
                    <h5>Lihat <i class="fa fa-arrow-circle-right"></i></h5>
                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Total Produk</h5>
            </div>
            <div class="ibox-content">
                <span class="pull-right"><i class="fa fa-cubes fa-5x"></i></span>
                <h1 class="no-margins font-bold">{{ $produk }}</h1>
                <br>
                <a href="{{ route('produk.index') }}">
                    <h5>Lihat <i class="fa fa-arrow-circle-right"></i></h5>
                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Total Member</h5>
            </div>
            <div class="ibox-content">
                <span class="pull-right"><i class="fa fa-vcard fa-5x"></i></span>
                <h1 class="no-margins font-bold">{{ $member }}</h1>
                <br>
                <a href="{{ route('member.index') }}">
                    <h5>Lihat <i class="fa fa-arrow-circle-right"></i></h5>
                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Total Supplier</h5>
            </div>
            <div class="ibox-content">
                <span class="pull-right"><i class="fa fa-truck fa-5x"></i></span>
                <h1 class="no-margins font-bold">{{ $supplier }}</h1>
                <br>
                <a href="{{ route('supplier.index') }}">
                    <h5>Lihat <i class="fa fa-arrow-circle-right"></i></h5>
                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Stock Tersedia</h5>
            </div>
            <div class="ibox-content">
                <span class="pull-right"><i class="fa fa-cube fa-5x"></i></span>
                <h1 class="no-margins font-bold">{{ $stock }} Pcs</h1>
                <br>
                <a href="{{ route('produk.index') }}">
                    <h5>Lihat <i class="fa fa-arrow-circle-right"></i></h5>
                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Pengeluaran</h5>
            </div>
            <div class="ibox-content">
                <span class="pull-right"><i class="fa fa-dollar fa-5x"></i></span>
                <h1 class="no-margins font-bold">Rp. {{ format_uang($pengeluaran) }},00</h1>
                <br>
                <a href="{{ route('pengeluaran.index') }}">
                    <h5>Lihat <i class="fa fa-arrow-circle-right"></i></h5>
                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Pemasukan</h5>
            </div>
            <div class="ibox-content">
                <span class="pull-right"><i class="fa fa-bank fa-5x"></i></span>
                <h1 class="no-margins font-bold">Rp. {{ format_uang($pemasukan) }},00</h1>
                
                <br>
                <a href="{{ route('pemasukan.index') }}">
                <h5>Lihat <i class="fa fa-arrow-circle-right"></i></h5>

                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Total Pendapatan</h5>
            </div>
            <div class="ibox-content">
                <span class="pull-right"><i class="fa fa-money fa-5x"></i></span>
                <h1 class="no-margins font-bold">Rp. {{ format_uang($hasil) }},00</h1>
                <br>
                <a href="{{ route('laporan.index') }}">
                    <h5>Lihat <i class="fa fa-arrow-circle-right"></i></h5>
                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Grafik Pendapatan {{ tanggal_indonesia($tanggal_awal, false) }} s/d
                    {{ tanggal_indonesia($tanggal_akhir, false) }}
                </h5>
            </div>
            <div class="ibox-content">
                <div>
                    <canvas id="lineChart" height="80"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>
    $(function () {

        var lineData = {
        labels: {{ json_encode($data_tanggal) }},
        datasets: [
            {
                label: "Pendapatan",
                backgroundColor: 'rgba(26,179,148,0.5)',
                borderColor: "rgba(26,179,148,0.7)",
                pointBackgroundColor: "rgba(26,179,148,1)",
                pointBorderColor: "#fff",
                data: {{ json_encode($data_pendapatan) }}
            }
        ]
    };

    var lineOptions = {
        responsive: true
    };


    var ctx2 = document.getElementById("lineChart").getContext("2d");
    new Chart(ctx2, {type: 'line', data: lineData, options:lineOptions});

});
</script>
@endpush